const cards = {
  forAdults: [
    { nameEng: '', nameRus: 'Клитор' },
    { nameEng: '', nameRus: 'Фаллос' },
    { nameEng: '', nameRus: 'Член' },
    { nameEng: '', nameRus: 'Вибратор' },
    { nameEng: '', nameRus: 'Матка' },
    { nameEng: '', nameRus: 'Спермотозоид' },
    { nameEng: '', nameRus: 'Сперма' },
    { nameEng: '', nameRus: 'Кончить' },
    { nameEng: '', nameRus: 'Эрекция' },
    { nameEng: '', nameRus: 'Минет' },
    { nameEng: '', nameRus: 'Вагина' },
    { nameEng: '', nameRus: 'Резиновый член' },
    { nameEng: '', nameRus: 'Гендер' },
    { nameEng: '', nameRus: 'Гермафродит' },
    { nameEng: '', nameRus: 'Гейша' },
    { nameEng: '', nameRus: 'Романтика' },
    { nameEng: '', nameRus: 'Женственность' },
    { nameEng: '', nameRus: 'Причиндалы' },
    { nameEng: '', nameRus: 'Менструация' },
    { nameEng: '', nameRus: 'поза 69' },
    { nameEng: '', nameRus: 'Влюбленность' },
    { nameEng: '', nameRus: 'Девственник' },
    { nameEng: '', nameRus: 'Наложница' },
    { nameEng: '', nameRus: 'Семейная ссора' },
    { nameEng: '', nameRus: 'Свидание' },
    { nameEng: '', nameRus: 'Трансгендер' },
    { nameEng: '', nameRus: 'Запретный плод' },
    { nameEng: '', nameRus: 'Животный инстинкт' },
    { nameEng: '', nameRus: 'Девиация' },
    { nameEng: '', nameRus: 'Гиперсексуальность' },
    { nameEng: '', nameRus: 'Любовница' },
    { nameEng: '', nameRus: 'Сексуальная энергия' },
    { nameEng: '', nameRus: 'Анилингус' },
    { nameEng: '', nameRus: 'Девичник' },
    { nameEng: '', nameRus: 'Совокупляться' },
    { nameEng: '', nameRus: 'Секс-шоп' },
    { nameEng: '', nameRus: 'Бой-френд' },
    { nameEng: '', nameRus: 'Женский оргазм' },
    { nameEng: '', nameRus: 'Клиторный оргазм' },
    { nameEng: '', nameRus: 'Горячая брюнетка' },
    { nameEng: '', nameRus: 'Мужское достоинство' },
    { nameEng: '', nameRus: 'Совокупление' },
    { nameEng: '', nameRus: 'Зона бикини' },
    { nameEng: '', nameRus: 'ПМС' },
    { nameEng: '', nameRus: 'Либидо' },
    { nameEng: '', nameRus: 'Влагалище' },
    { nameEng: '', nameRus: 'Флирт' },
    { nameEng: '', nameRus: 'Обручение' },
    { nameEng: '', nameRus: 'Оголенный торс' },
    { nameEng: '', nameRus: 'Романтик' },
    { nameEng: '', nameRus: 'Оральные ласки' },
    { nameEng: '', nameRus: 'Секс-машина' },
    { nameEng: '', nameRus: 'Анальная пробка' },
    { nameEng: '', nameRus: 'Наездница' },
    { nameEng: '', nameRus: 'Соблазнение' },
    { nameEng: '', nameRus: 'Феромоны' },
    { nameEng: '', nameRus: 'Насиловать' },
    { nameEng: '', nameRus: 'Гей-парад' },
    { nameEng: '', nameRus: 'Лезбийская любовь' },
    { nameEng: '', nameRus: 'Эксгибиционист' },
    { nameEng: '', nameRus: 'Полигамный партнер' },
    { nameEng: '', nameRus: 'День святого Валентина' },
    { nameEng: '', nameRus: 'Ревнивый' },
    { nameEng: '', nameRus: 'Беременность' },
    { nameEng: '', nameRus: 'Вагинальный оргазм' },
    { nameEng: '', nameRus: 'Семейный очаг' },
  ],
  main: [
    { nameEng: 'Bus', nameRus: 'Автобус' },
    { nameEng: '', nameRus: 'Дом' },
    { nameEng: '', nameRus: 'Мост' },
    { nameEng: '', nameRus: 'Лупа' },
    { nameEng: '', nameRus: 'Перец' },
    { nameEng: '', nameRus: 'Город' },
    { nameEng: '', nameRus: 'Морж' },
    { nameEng: '', nameRus: 'Пират' },
    { nameEng: '', nameRus: 'Море' },
    { nameEng: '', nameRus: 'Яблоко' },
    { nameEng: '', nameRus: 'Акула' },
    { nameEng: '', nameRus: 'Солнце' },
    { nameEng: '', nameRus: 'Шарик' },
    { nameEng: '', nameRus: 'Пластилин' },
    { nameEng: '', nameRus: 'Ведро' },
    { nameEng: '', nameRus: 'Начальник' },
    { nameEng: '', nameRus: 'Пылесос' },
    { nameEng: '', nameRus: 'Аквариум' },
    { nameEng: '', nameRus: 'Монитор' },
    { nameEng: '', nameRus: 'Чеснок' },
    { nameEng: '', nameRus: 'Страус' },
    { nameEng: '', nameRus: 'Расстояние' },
    { nameEng: '', nameRus: 'Лень' },
    { nameEng: '', nameRus: 'Дым' },
    { nameEng: '', nameRus: 'Укус' },
    { nameEng: '', nameRus: 'Комар' },
    { nameEng: '', nameRus: 'Спортсмен' },
    { nameEng: '', nameRus: 'Провод' },
    { nameEng: '', nameRus: 'Мотор' },
    { nameEng: '', nameRus: 'Жена' },
    { nameEng: '', nameRus: 'Сок' },
    { nameEng: '', nameRus: 'Береза' },
    { nameEng: '', nameRus: 'Ваза' },
    { nameEng: '', nameRus: 'Рыба' },
    { nameEng: '', nameRus: 'Соловей' },
    { nameEng: '', nameRus: 'Озеро' },
    { nameEng: '', nameRus: 'Кошелек' },
    { nameEng: '', nameRus: 'Луна' },
    { nameEng: '', nameRus: 'Дед' },
    { nameEng: '', nameRus: 'Календарь' },
    { nameEng: '', nameRus: 'Лопата' },
    { nameEng: '', nameRus: 'Качели' },
    { nameEng: '', nameRus: 'Страх' },
    { nameEng: '', nameRus: 'Сумка' },
    { nameEng: '', nameRus: 'Окно' },
    { nameEng: '', nameRus: 'Собака' },
    { nameEng: '', nameRus: 'Друзья' },
    { nameEng: '', nameRus: 'Ребенок' },
    { nameEng: '', nameRus: 'Месяц' },
    { nameEng: '', nameRus: 'Котенок' },
    { nameEng: '', nameRus: 'Конфета' },
    { nameEng: '', nameRus: 'Праздник' },
    { nameEng: '', nameRus: 'Сон' },
    { nameEng: '', nameRus: 'Скелет' },
    { nameEng: '', nameRus: 'Лодка' },
    { nameEng: '', nameRus: 'Остров' },
    { nameEng: '', nameRus: 'Браслет' },
    { nameEng: '', nameRus: 'Хлеб' },
    { nameEng: '', nameRus: 'Курица' },
    { nameEng: '', nameRus: 'Крыша' },
    { nameEng: '', nameRus: 'Жилет' },
    { nameEng: '', nameRus: 'Дневник' },
    { nameEng: '', nameRus: 'Мусор' },
    { nameEng: '', nameRus: 'Автомобиль' },
    { nameEng: '', nameRus: 'Девочка' },
    { nameEng: '', nameRus: 'Туфли' },
    { nameEng: '', nameRus: 'Вафли' },
    { nameEng: '', nameRus: 'Донор' },
    { nameEng: '', nameRus: 'Семечки' },
    { nameEng: '', nameRus: 'Телефон' },
    { nameEng: '', nameRus: 'Гроза' },
    { nameEng: '', nameRus: 'Скрепка' },
    { nameEng: '', nameRus: 'Радость' },
    { nameEng: '', nameRus: 'Мел' },
    { nameEng: '', nameRus: 'Бумага' },
    { nameEng: '', nameRus: 'Мышка' },
    { nameEng: '', nameRus: 'Зубы' },
    { nameEng: '', nameRus: 'Нос' },
    { nameEng: '', nameRus: 'Трава' },
    { nameEng: '', nameRus: 'Варежки' },
    { nameEng: '', nameRus: 'Швабра' },
    { nameEng: '', nameRus: 'Парик' },
    { nameEng: '', nameRus: 'Карандаш' },
    { nameEng: '', nameRus: 'Лекарство' },
    { nameEng: '', nameRus: 'Юбка' },
    { nameEng: '', nameRus: 'Лев' },
    { nameEng: '', nameRus: 'Град' },
    { nameEng: '', nameRus: 'База' },
    { nameEng: '', nameRus: 'Ноты' },
    { nameEng: '', nameRus: 'Радиация' },
    { nameEng: '', nameRus: 'Посуда' },
    { nameEng: '', nameRus: 'Кондиционер' },
    { nameEng: '', nameRus: 'Парад' },
    { nameEng: '', nameRus: 'Чашка' },
    { nameEng: '', nameRus: 'Порошок' },
    { nameEng: '', nameRus: 'Список' },
    { nameEng: '', nameRus: 'Фотограф' },
    { nameEng: '', nameRus: 'Черепаха' },
    { nameEng: '', nameRus: 'Звезда' },
    { nameEng: '', nameRus: 'Колпак' },
    { nameEng: '', nameRus: 'Барабан' },
    { nameEng: '', nameRus: 'Брюки' },
    { nameEng: '', nameRus: 'Тётя' },
    { nameEng: '', nameRus: 'Брошка' },
    { nameEng: '', nameRus: 'Улыбка' },
    { nameEng: '', nameRus: 'Палка' },
    { nameEng: '', nameRus: 'Блоднинка' },
    { nameEng: '', nameRus: 'Пост' },
    { nameEng: '', nameRus: 'Букет' },
    { nameEng: '', nameRus: 'Штраф' },
    { nameEng: '', nameRus: 'Смех' },
    { nameEng: '', nameRus: 'Цирк' },
    { nameEng: '', nameRus: 'Маркер' },
    { nameEng: '', nameRus: 'Хорек' },
    { nameEng: '', nameRus: 'Клетка' },
    { nameEng: '', nameRus: 'Письмо' },
    { nameEng: '', nameRus: 'Кнопка' },
  ],
};

export default cards;
